name: Update ClashX config

on:
  push:
    paths:
      - "Server.txt"
  workflow_dispatch: {}   # ручной запуск из вкладки Actions

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # нужно, чтобы запушить изменения обратно
    env:
      SERVER_FILE: Server.txt
      TARGET_FILE: proxy for clashx pro.yaml
      GROUPS_TO_FILL: PROXY,GLOBAL,节点选择,Proxy
    steps:
      - uses: actions/checkout@v4

      - name: Show tree (debug)
        run: |
          pwd
          ls -al
          ls -al scripts || true
          ls -al ".github/workflows" || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install ruamel.yaml requests

      - name: Run updater
        run: python scripts/update_clash.py

      - name: Commit & push
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add "proxy for clashx pro.yaml"
            git commit -m "auto: update clashx config from Server.txt"
            git push
          else
            echo "No changes"
          fi
